### ISSUE TITLE
How to statistics the novel transcripts

### ISSUE THREAD

**Issue by Trandamere** [gpertea/gffcompare#10]
Hello,
    I read the Transcript-level expression analysis of RNA-seq experiments with HISAT, StringTie and Ballgown.
then I download the file chrX_data.tar.gz to practice.
    I have a problem for novel transcripts. I use one simple,ERR188044,to practice ,like this:
gffcompare -r /disk/chrX_data/genes/chrX.gtf -G -o /disk/luping/chrX_data/gffcompare/ERR188044 /disk/chrX_data/gtf/ERR188044_chrX.gtf. 

#= Summary for dataset: /disk/chrX_data/gtf/ERR188044_chrX.gtf 
#     Query mRNAs :    1234 in     786 loci  (890 multi-exon transcripts)
#            (226 multi-transcript loci, ~1.6 transcripts per locus)
# Reference mRNAs :    2102 in    1086 loci  (1856 multi-exon)
# Super-loci w/ reference transcripts:      461
#-----------------| Sensitivity | Precision  |
        Base level:    51.6     |    80.3    |
        Exon level:    46.7     |    85.4    |
      Intron level:    47.2     |    93.8    |
Intron chain level:    31.2     |    65.2    |
  Transcript level:    31.6     |    53.8    |
       Locus level:    36.6     |    50.6    |

     Matching intron chains:     580
       Matching transcripts:     664
              Matching loci:     397

          Missed exons:    4398/8804	( 50.0%)
           Novel exons:     418/4863	(  8.6%)
        Missed introns:    3832/7946	( 48.2%)
         Novel introns:      79/3995	(  2.0%)
           Missed loci:     581/1086	( 53.5%)
            Novel loci:     260/786	( 33.1%)

 Total union super-loci across all input datasets: 741 
1234 out of 1234 consensus transcripts written in /disk/luping/chrX_data/gffcompare/ERR188044.annotated.gtf (0 discarded as redundant)

then I statistics the novel transcripts using  class_code "j",but this is different from the results of table7

ERR188044   Novel transcripts 615 Did I have any mistake?

**Comment by naveenkumarv40** [comment]
Hello Trandamere,
         I am also new to RNA-SEQ analysis. I also followed this same protocol for my dataset. And i am having some problem for identifying novel transcripts and genes from the below gffcompare ".stats" file

 i was running the following command $ gffcompare –r chrX_data/genes/chrX.gtf –G –o merged stringtie_merged.gtf. and i got the result file as
= Summary for dataset: stringtie_merged.gtf
Query mRNAs : 253181 in 70635 loci (216728 multi-exon transcripts)
(23264 multi-transcript loci, ~3.6 transcripts per locus)
Reference mRNAs : 216257 in 60158 loci (189357 multi-exon)
Super-loci w/ reference transcripts: 51791
-----------------| Sensitivity | Precision |

    Base level:   100.0     |    93.0    |
    Exon level:    99.9     |    93.6    |
  Intron level:    99.4     |    94.0    |

Intron chain level: 99.7 | 87.1 | Transcript level: 99.8 | 85.2 | Locus level: 100.0 | 84.4 |

 Matching intron chains:  188838
   Matching transcripts:  215729
          Matching loci:   60158

      Missed exons:       0/623537  (  0.0%)
       Novel exons:   23741/674273  (  3.5%)
    Missed introns:    2160/383827  (  0.6%)
     Novel introns:    4747/405880  (  1.2%)
       Missed loci:       0/60158   (  0.0%)
        Novel loci:   10239/70635   ( 14.5%)

Total union super-loci across all input datasets: 70632 253181 out of 253181 consensus transcripts written in merged.annotated.gtf (0 discarded as redundant).  

from this result where i can find the novel genes and transcripts?

**Comment by gpertea** [comment]
Closing this as it is generally addressed in the answer to #24 and the online documentation.
