### ISSUE TITLE
How to interpret sensitivity and precision?

### ISSUE THREAD

**Issue by Vivianstats** [gpertea/gffcompare#11]
Hello,

Thank you very much for this helpful tool. But I'd like to ask how are sensitivity and precision at different levels (bases, exons, transcripts) calculated? In other words, how do you define a "truth positive" or a "match"? Can you provide more details here?

Thanks!

**Comment by Jwaj** [comment]
Hi Vivianstats,

Did you find way to interpret the sensitivity and precision at different levels (bases, exons, transcripts) calculated?

Thanks

**Comment by gpertea** [comment]
Apologies for not clarifying this a while ago, it had been mentioned back in the days of CuffCompare but never got this documented properly for GffCompare. 
I added some comments about this on the new GffCompare documentation webpage: 
http://ccb.jhu.edu/software/stringtie/gffcompare.shtml#output-files

Copied also below for the sake of completion:

These accuracy measures are calculated under the assumption that the input GFF/GTF file(s) (the "query" transcripts, or transfrags, from one or multiple "samples") are coming from some transcript discovery/assembly pipeline (e.g. Cufflinks or StringTie), or from any other gene/transcript prediction pipeline. GffCompare can be used to assess the accuracy of such pipelines, when comparing their results to a known reference annotation (provided with the ```-r``` option). The measures of “sensitivity” and “precision” are calculated at various levels (nucleotide, exon, intron, transcript, gene) for each input file and reported in this ```.stats``` file.
These generic accuracy metrics are calculated as described in Burset, M., Guigó, R. : Evaluation of gene structure prediction programs (1996) Genomics, 34 (3), pp. 353-367. [doi: 10.1006/geno.1996.0298](http://dx.doi.org/10.1006/geno.1996.0298) (please note that in that paper the authors used the term _“Specificity”_ for what we currently call “_Precision”_). The following general formulae are used for calculation of Sensitivity and Precision at various levels (base, exon, intron chain, transcript, gene):

       Sensitivity = TP / (TP+FN)     Precision = TP / (TP+FP)

Here TP means "true positives", which in this case are the query features (bases, exons, introns, transcripts, etc.) which agree with the corresponding reference annotation features. FN means "false negatives", i.e. features which are found in the reference annotation but missed (not present) in the "query" data. Accordingly, FP are features present in the input "query" data but not confirmed by any reference annnotation data. Notice that FP+TP amounts to the whole input set of "query" features (per sample/input file). If multiple "query" GTF/GFF files are given as input, these metrics are computed separately for each sample.
