### ISSUE TITLE
update release tags

### ISSUE THREAD

**Issue by 0xaf1f** [gpertea/gffcompare#15]
We're installing gffcompare on our cluster and it would help us to quickly find and update to the latest stable release if you could keep the tags up-to-date. The latest tag says 0.9.8, but the version string in gffcompare.cpp says 0.9.9d.

Many thanks for your consideration

**Comment by gpertea** [comment]
You're correct, I apologize for not being consistent on this (and for catching up to this issue almost an year later..). The current v0.10.2 should be now tagged properly and I'll try to keep it this way..
