### ISSUE TITLE
gffcompare class code "x", what is the minimum overlap?

### ISSUE THREAD

**Issue by dgelsin** [gpertea/gffcompare#22]
Hello,

What is the minimum overlap required on the opposite strand for the class code "x" to be assigned? I am curious if this can be altered at all within the script as I am interested in search for antisense transcription in my dataset but would like to know how that is being classified using gffcompare. I've looked in your papers and in the cuffcompare repository/website but can't seem to find this information.

Any help is appreciated!

Thank you,

Diego

**Comment by gpertea** [comment]
Unfortunately that class code is currently reported for any >=1bp overlap on the opposite strand.. 
As a side note, the gffcompare documentation has been updated recently (see http://ccb.jhu.edu/software/stringtie/gffcompare.shtml) with a diagram documenting these and other (newer) codes that were added to gffcompare. For example the new code ```'s'``` is much more specific as it also involves an intron overlap -- though obviously this is only helpful for multi-exon transcripts. 

The C++ code actually retrieves the overlap length but the value is never exposed in the output files produced by gffcompare. 
I was playing recently with a faster transcript classification code, temporarily called trmap (full code is in https://github.com/gpertea/trmap) which outputs the full exon structures (along with the class code) of both transcript query along with the overlapped references; I could easily modify that tool to also output the overlap length -- or one can use a post-processing script to filter those ```'x'``` overlaps as needed, based on the exon coordinates.
Eventually this trmap code will likely become part of gffcompare.. but until then it's functional on its own for such quick transcript classification.
