### ISSUE TITLE
Why the total transcripts in the .tmp file was less than the total transcripts in the  input .gtf file

### ISSUE THREAD

**Issue by syy2017** [gpertea/gffcompare#23]
Hi,
I am taking a few stringtie assemblies of human single-cell  RNAseq data and annotating them back against Gencode v27 gtf files using gffcompare. I have noticed some differences between the total number of transcripts in the one input.gtf  and the output file of .tmap after I used the many default modes of gffcompare.
The command is used as follows:
gffcompare-0.10.1.Linux_x86_64/gffcompare -R -r  /ReferenceAnnotation/gencode.v27.annotation.gtf -G  
-o gffResultPrefix stringtie_result/SRR.gtf  
I  have got some information about the differences between the "GffCompare" and "CuffCompare" from the website at https://github.com/gpertea/gffcompare, as follows:
    Another important difference is that the input transcripts are no longer discarded when they are found to be "intron redundant", i.e. contained within other, longer isoforms. CuffCompare had the -G option to prevent collapsing of such intron redundant isoforms into their longer "containers", but GffCompare has made this the default mode of operation (hence the -G option is no longer needed and is simply ignored when given).
Maybe I am missing something obvious, so could you please give advice on how I can run the newest version of gffcompare to preserve the missing transcripts?

**Comment by gpertea** [comment]
This seems to be related to the long standing bug where GffCompare used to discard "duplicate" transcripts even in *"annotation mode"*. This should be now fixed in release v0.10.2.
