### ISSUE TITLE
How can I extract the novel exons?

### ISSUE THREAD

**Issue by ashokpatowary** [gpertea/gffcompare#34]
I am having the following statistic from gffcompare

          Missed exons:   81439/302312  ( 26.9%)
           Novel exons:    2536/146326  (  1.7%)
        Missed introns:   38931/183784  ( 21.2%)
         Novel introns:     556/100652  (  0.6%)
           Missed loci:       0/11150   (  0.0%)
            Novel loci:     166/10328   (  1.6%)

I can see there is 2536 novel exons in my input file. Is there any way I can extract this exons?

Thanks

**Comment by gpertea** [comment]
gffcompare does not provide a way to do this. I'd suggest looking into something like **bedtools** which I think can perform various exon interval queries between two GFF files, etc.

**Comment by ashokpatowary** [comment]
Thanks for your response. I tried bedtools. Bedtools give me 340 novel exon but gffcompare (though used for difference purpose) gave me 2536 novel exons. So, I was trying to see whats the difference. Anyways thanks.
