### ISSUE TITLE
Sensitivity/Precision Stats

### ISSUE THREAD

**Issue by helenistheking** [gpertea/gffcompare#35]
For the stats produced by gffcompare. Can you explain how they are calculated? 
If, 𝑷𝒓𝒆𝒄𝒊𝒔𝒊𝒐𝒏=𝑻𝑷/(𝑻𝑷+𝑭𝑷)
What is a false positive?
And how do you calculate this on the 'base level'?

```
 #-----------------| Sensitivity | Precision  |      
 Base level:    82.4     |    76.5    |
        Exon level:    81.2     |    82.9    |
      Intron level:    86.1     |    94.8    |
Intron chain level:    56.9     |    52.4    |
  Transcript level:    55.2     |    38.9    |
       Locus level:    70.1     |    48.0    |
```

**Comment by gpertea** [comment]
I just updated the official documentation to include some description of how these values are calculated at various levels: http://ccb.jhu.edu/software/stringtie/gffcompare.shtml#levels
Most of these were also previously described in the 1996 Burset & Guigo paper referenced on that page.

**Comment by helenistheking** [comment]
Thank you!
