### ISSUE TITLE
Missing tmap and refmap files

### ISSUE THREAD

**Issue by fgypas** [gpertea/gffcompare#43]
Hi

I tried version 0.11.2 (from anaconda) and 0.11.4 (precompiled binary) as following:

```
gffcompare \
-r reference.gtf \
-s .genome.fa \
-o prefix \
merged_annotation.gtf
```
where merged_annotation.gtf is the output of stringtie merge. After this run I get the following files:

- .tracking
- .annotated.gtf
- .loci
- .stats

but I am missing the .tmap and .refmap

Am I doing something wrong?

Thank you in advance
Foivos

**Comment by fgypas** [comment]
OK, I just saw #8

**Comment by gpertea** [comment]
Indeed, that was the problem - I cannot guarantee the uniqueness of the per-sample output files when multiple "query" samples are provided, unless I write them into their original directories..

Also, please use the latest binary precompiled version (or compile the latest released version from source, if you prefer) as there could be sometimes bugs that I fix and then I immediately release the new version, while the anaconda version usually lags behind and could be the "buggy" one that I just fixed (duh).
