### ISSUE TITLE
make: *** [gffcompare.o] Error 1

### ISSUE THREAD

**Issue by OscarChou211** [gpertea/gffcompare#56]
Hi there, 

I am trying to install the gffcompare. Below are my commands. I wonder what are the problems? Thank you! 

I used the GitHub: git clone https://github.com/gpertea/gffcompare 

apple@apples-MBP-2 gffcompare % make release
c++ -O3 -DNDEBUG -std=c++0x -Wall -Wextra -I../gclib -D_REENTRANT -fno-exceptions -fno-rtti -Wno-class-memaccess -c gffcompare.cpp -o gffcompare.o
warning: unknown warning option '-Wno-class-memaccess'; did you mean '-Wno-class-varargs'? [-Wunknown-warning-option]
gffcompare.cpp:802:17: error: no matching function for call to 'transcriptMatch'
                  char tmatch=transcriptMatch(*(super->qmrnas[i]),*(super->rmrnas[j]), ovlen, terminalMatchRange);
                              ^~~~~~~~~~~~~~~
../gclib/gff.h:63:6: note: candidate function not viable: requires 3 arguments, but 4 were provided
char transcriptMatch(GffObj& a, GffObj& b, int& ovlen); //generic transcript match test
     ^
1 warning and 1 error generated.
make: *** [gffcompare.o] Error 1

**Comment by gpertea** [comment]
Is it possible that you already had an older copy of gclib in the parent directory there (../gclib)? If so, you may want to remove that directory and try the `make release` command again, which should pull the latest version of gclib as needed. 
Even better would be to download and compile the prepared source package  `gffcompare-0.11.7.tar.gz` either from the releases page (https://github.com/gpertea/gffcompare/releases) or from the official web page (http://ccb.jhu.edu/software/stringtie/gffcompare.shtml#gffcompare_dl), that package always has the latest/matching version of gclib included needed, it is self-contained.

**Comment by OscarChou211** [comment]
I see! It is working now for me after I have download and compile the prepared source package! Thank you very much for helping!
