### ISSUE TITLE
make: *** [Makefile:61: ../gclib] Error 127

### ISSUE THREAD

**Issue by yejilee-biostat** [gpertea/gffcompare#57]
Hello,

 I tried to install gffcompare on centos from source codes on the github, and it gave me the following message : 

===================
> make release
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 1171 (delta 14), reused 24 (delta 9), pack-reused 1140
Receiving objects: 100% (1171/1171), 840.29 KiB | 340.00 KiB/s, done.
Resolving deltas: 100% (777/777), done.
Cloning into 'gclib'...
make: Cloning: Command not found
make: *** [Makefile:61: ../gclib] Error 127
====================

I'm trying to use the pre-compiled version for now, but I'm still curious about this issue. Could you help me to solve this issue? Thank you.

-Yeji

**Comment by gpertea** [comment]
Ouch, there was indeed a mistake in the Makefile that seemed to not cause problems on newer Linux distros but failed on CentOS. I corrected that and re-released v0.11.7 source with that simple Makefile fix. 
Could you try again with the updated Makefile? 

Thank you for pointing out this build problem.

**Comment by yejilee-biostat** [comment]
Sorry for not replying for so long - I have been using the pre-compiled version and forgot about this issue.
I have tried to compile the updated version, and now it gives me the new kind of errors

====
...
/home/tools/yejilee/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -O3 -DNDEBUG -std=c++0x -Wall -Wextra -I../gclib -D_REENTRANT -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/tools/yejilee/miniconda3/include -c gffcompare.cpp -o gffcompare.o
g++ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath /home/tools/yejilee/miniconda3/lib -Wl,-rpath-link,/home/tools/miniconda3/lib -L /home/tools/yejilee/miniconda3/lib -o gffcompare ../gclib/GFastaIndex.o ../gclib/GFaSeqGet.o ../gclib/gff.o ../gclib/gdna.o ../gclib/codons.o ../gclib/GBase.o ../gclib/GStr.o ../gclib/GArgs.o gtf_tracking.o gffcompare.o
/usr/bin/ld: ../gclib/gff.o: unrecognized relocation (0x29) in section `.text._ZN5GPVecI7GffExonE15DefaultFreeProcEPv[_ZN5GPVecI7GffExonE15DefaultFreeProcEPv]'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: gffcompare] Error 1
=====

I am not sure it is a problem caused by my local setting or source codes. But the pre-compiled version seems working well for me, so I will probably not dig into this issue any further. Still, thank you for your kind reply!
