### ISSUE TITLE
gffcompare -d option not having effect

### ISSUE THREAD

**Issue by Akazhiel** [gpertea/gffcompare#63]
Hello, I've tried running gffcompare with extreme values on the -d parameter and to my surprise all the merged transcripts came out the same size. Is it not having effect or am I misunderstanding the function of this parameter?

**Comment by gpertea** [comment]
That parameter only controls the `tss_id` attribute assignments (grouping transcripts by TSS location). It has no influence over the merging of transcripts which is only controlled by structural matching (same intron chain or, in the case of single-exon transcripts, well-bounded overlaps)
