### ISSUE TITLE
Where can I get gffcompare v0.12.5?

### ISSUE THREAD

**Issue by junghoon-shin** [gpertea/gffcompare#66]
According to [this](https://github.com/gpertea/gffcompare/issues/58#issuecomment-752968020), the last version of gffcompare should be v0.12.5 or later, but the [release notes](https://github.com/gpertea/gffcompare/releases) indicate the last updated version is v0.12.2. Where can I get the latest version?

**Comment by gpertea** [comment]
Indeed, I did not make an official release since v0.12.2, sorry about that lapse, and thank you for pointing it out. 
 v0.12.6 is now available, from https://ccb.jhu.edu/software/stringtie/gffcompare.shtml#gffcompare_dl or https://github.com/gpertea/gffcompare/releases/latest
