### ISSUE TITLE
Transcript classification codes ?

### ISSUE THREAD

**Issue by hmyh1202** [gpertea/gffcompare#74]
Hi，

   which code is potentially novel isoform ?

Thank you.

**Comment by gpertea** [comment]
If you are looking for novel alternative splicing isoform (with novel junctions), code `j` might be the more "promissing" one. See the table at http://ccb.jhu.edu/software/stringtie/gffcompare.shtml#transfrag-class-codes 
However there are other codes that can potentially capture that - even `k` (reverse containment) or `o` (other unclassified overlap) could be revealed to be a novel isoform. Of course, transcriptional noise, alignment artifacts and even assembly issues (fragmentation, coverage bias etc.) should be considered. 

One could argue that even code `=` (matching) could in fact hide a potentially novel isoform - one with a different TSS and/or TES, perhaps. 

So the most disappointingly encompassing answer to your question could be:  _"all of them"_.
